package org.demo.demoapplication;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey
    private String email;
//    @DynamoDBRangeKey
//    @DynamoDBAutoGeneratedKey
//    private int id;

    @DynamoDBRangeKey
    private String role;

    private String password;

    public User(String username) {
        this.email = username;
    }
}
